org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

mc_version=26.1.2
mc_version_range=[26.1.2]
neo_version=26.1.2.109

mod_id=nexus
mod_name=Nexus
mod_license=MIT
mod_version=1.0.0
mod_version_type=alpha
mod_group_id=dev.satherov.nexus
